name: HW1_performance

on:
  push

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Use Go = 1.21
        uses: actions/setup-go@v3
        with:
          go-version: "=1.21"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Install gotestfmt on the VM running the action.
      - name: Set up gotestfmt
        uses: gotesttools/gotestfmt-action@v2
        with:
          # Pass GITHUB_TOKEN to avoid rate limiting.
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Portaudio
        run: |
          sudo apt-get update
          sudo apt-get install -y portaudio19-dev

      - name: Create temp directory
        run: |
          mkdir -p ./${{ github.run_attempt }}

      - name: Test HW1 Performance
        if: always()
        run: |
          set -euo pipefail
          make test_bench_hw1 2>&1 | tee ./${{ github.run_attempt }}/goperf-hw1.log | gotestfmt
        env:
          GLOG: no
          BINLOG: no
          HTTPLOG: no
          JSONIFY: "-json"

      # Upload formatted logs
      - name: Upload HW1 performance test log
        uses: actions/upload-artifact@v2
        with:
          name: perf-test-hw1-log
          path: ./${{ github.run_attempt }}/goperf-hw1.log
          if-no-files-found: error
