name: Grading

on:
  push
  
jobs:
  linter:
    runs-on:
      group: runners_v1
    outputs:
      result: ${{ steps.vet.outcome }}
    steps:
      - name: Use Go = 1.21
        uses: actions/setup-go@v3
        with:
          go-version: '=1.21'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Tidy
        run: go mod tidy && [ -z "$(git status -s)" ]

      - name: Lint
        run: make lint

      - name: Vet
        id: vet
        run: make vet
  Test_HW0_Integration_Unicast:
    runs-on:
      group: runners_v1
    outputs:
      result: ${{ steps.test.outcome }}
    steps:
      - name: Use Go = 1.21
        uses: actions/setup-go@v3
        with:
          go-version: '=1.21'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Run unit tests
        id: test
        run: go test ./... -race -run "Test_HW0_Integration_Unicast" --timeout=5m

  Test_HW0_Network_Listen_Close:
    runs-on:
      group: runners_v1
    outputs:
      result: ${{ steps.test.outcome }}
    steps:
      - name: Use Go = 1.21
        uses: actions/setup-go@v3
        with:
          go-version: '=1.21'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Run unit tests
        id: test
        run: go test ./... -race -run "Test_HW0_Network_Listen_Close" --timeout=15s

  Test_HW0_Network_Simple:
    runs-on:
      group: runners_v1
    outputs:
      result: ${{ steps.test.outcome }}
    steps:
      - name: Use Go = 1.21
        uses: actions/setup-go@v3
        with:
          go-version: '=1.21'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Run unit tests
        id: test
        run: go test ./... -race -run "Test_HW0_Network_Simple" --timeout=15s

  Test_HW0_Network_Multiple:
    runs-on:
      group: runners_v1
    outputs:
      result: ${{ steps.test.outcome }}
    steps:
      - name: Use Go = 1.21
        uses: actions/setup-go@v3
        with:
          go-version: '=1.21'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Run unit tests
        id: test
        run: go test ./... -race -run "Test_HW0_Network_Multiple" --timeout=15s

  Test_HW0_Messaging_AddPeer:
    runs-on:
      group: runners_v1
    outputs:
      result: ${{ steps.test.outcome }}
    steps:
      - name: Use Go = 1.21
        uses: actions/setup-go@v3
        with:
          go-version: '=1.21'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Run unit tests
        id: test
        run: go test ./... -race -run "Test_HW0_Messaging_AddPeer" --timeout=15s

  Test_HW0_Messaging_SetRoutingEntry:
    runs-on:
      group: runners_v1
    outputs:
      result: ${{ steps.test.outcome }}
    steps:
      - name: Use Go = 1.21
        uses: actions/setup-go@v3
        with:
          go-version: '=1.21'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Run unit tests
        id: test
        run: go test ./... -race -run "Test_HW0_Messaging_SetRoutingEntry" --timeout=15s

  Test_HW0_Service_RegisterNotify-channel_transport:
    runs-on:
      group: runners_v1
    outputs:
      result: ${{ steps.test.outcome }}
    steps:
      - name: Use Go = 1.21
        uses: actions/setup-go@v3
        with:
          go-version: '=1.21'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Run unit tests
        id: test
        run: go test ./... -race -run "Test_HW0_Service_RegisterNotify/channel_transport" --timeout=15s

  Test_HW0_Service_RegisterNotify-UDP_transport:
    runs-on:
      group: runners_v1
    outputs:
      result: ${{ steps.test.outcome }}
    steps:
      - name: Use Go = 1.21
        uses: actions/setup-go@v3
        with:
          go-version: '=1.21'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Run unit tests
        id: test
        run: go test ./... -race -run "Test_HW0_Service_RegisterNotify/UDP_transport" --timeout=15s

  Test_HW0_Messaging_Unicast-channel_transport:
    runs-on:
      group: runners_v1
    outputs:
      result: ${{ steps.test.outcome }}
    steps:
      - name: Use Go = 1.21
        uses: actions/setup-go@v3
        with:
          go-version: '=1.21'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Run unit tests
        id: test
        run: go test ./... -race -run "Test_HW0_Messaging_Unicast/channel_transport" --timeout=15s

  Test_HW0_Messaging_Unicast-UDP_transport:
    runs-on:
      group: runners_v1
    outputs:
      result: ${{ steps.test.outcome }}
    steps:
      - name: Use Go = 1.21
        uses: actions/setup-go@v3
        with:
          go-version: '=1.21'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Run unit tests
        id: test
        run: go test ./... -race -run "Test_HW0_Messaging_Unicast/UDP_transport" --timeout=15s

  Test_HW0_Messaging_Unicast_Fail-channel_transport:
    runs-on:
      group: runners_v1
    outputs:
      result: ${{ steps.test.outcome }}
    steps:
      - name: Use Go = 1.21
        uses: actions/setup-go@v3
        with:
          go-version: '=1.21'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Run unit tests
        id: test
        run: go test ./... -race -run "Test_HW0_Messaging_Unicast_Fail/channel_transport" --timeout=15s

  Test_HW0_Messaging_Unicast_Fail-UDP_transport:
    runs-on:
      group: runners_v1
    outputs:
      result: ${{ steps.test.outcome }}
    steps:
      - name: Use Go = 1.21
        uses: actions/setup-go@v3
        with:
          go-version: '=1.21'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Run unit tests
        id: test
        run: go test ./... -race -run "Test_HW0_Messaging_Unicast_Fail/UDP_transport" --timeout=15s

  Test_HW0_Messaging_Relaying-channel_transport:
    runs-on:
      group: runners_v1
    outputs:
      result: ${{ steps.test.outcome }}
    steps:
      - name: Use Go = 1.21
        uses: actions/setup-go@v3
        with:
          go-version: '=1.21'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Run unit tests
        id: test
        run: go test ./... -race -run "Test_HW0_Messaging_Relaying/channel_transport" --timeout=15s

  Test_HW0_Messaging_Relaying-UDP_transport:
    runs-on:
      group: runners_v1
    outputs:
      result: ${{ steps.test.outcome }}
    steps:
      - name: Use Go = 1.21
        uses: actions/setup-go@v3
        with:
          go-version: '=1.21'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Run unit tests
        id: test
        run: go test ./... -race -run "Test_HW0_Messaging_Relaying/UDP_transport" --timeout=15s

  result_collector:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [ linter, Test_HW0_Integration_Unicast, Test_HW0_Network_Listen_Close, Test_HW0_Network_Simple, Test_HW0_Network_Multiple, Test_HW0_Messaging_AddPeer, Test_HW0_Messaging_SetRoutingEntry, Test_HW0_Service_RegisterNotify-channel_transport, Test_HW0_Service_RegisterNotify-UDP_transport, Test_HW0_Messaging_Unicast-channel_transport, Test_HW0_Messaging_Unicast-UDP_transport, Test_HW0_Messaging_Unicast_Fail-channel_transport, Test_HW0_Messaging_Unicast_Fail-UDP_transport, Test_HW0_Messaging_Relaying-channel_transport, Test_HW0_Messaging_Relaying-UDP_transport ]
    permissions: write-all
    steps:
      - name: Create empty result file
        run: echo -n "" > result.csv

      - name: Collect lint result
        run: echo "linter, ${{needs.linter.outputs.result}}" >> result.csv


      - name: Retrieve result of Test_HW0_Integration_Unicast
        run: echo "Test_HW0_Integration_Unicast, ${{needs.Test_HW0_Integration_Unicast.outputs.result}}" >> result.csv
      - name: Retrieve result of Test_HW0_Network_Listen_Close
        run: echo "Test_HW0_Network_Listen_Close, ${{needs.Test_HW0_Network_Listen_Close.outputs.result}}" >> result.csv
      - name: Retrieve result of Test_HW0_Network_Simple
        run: echo "Test_HW0_Network_Simple, ${{needs.Test_HW0_Network_Simple.outputs.result}}" >> result.csv
      - name: Retrieve result of Test_HW0_Network_Multiple
        run: echo "Test_HW0_Network_Multiple, ${{needs.Test_HW0_Network_Multiple.outputs.result}}" >> result.csv
      - name: Retrieve result of Test_HW0_Messaging_AddPeer
        run: echo "Test_HW0_Messaging_AddPeer, ${{needs.Test_HW0_Messaging_AddPeer.outputs.result}}" >> result.csv
      - name: Retrieve result of Test_HW0_Messaging_SetRoutingEntry
        run: echo "Test_HW0_Messaging_SetRoutingEntry, ${{needs.Test_HW0_Messaging_SetRoutingEntry.outputs.result}}" >> result.csv
      - name: Retrieve result of Test_HW0_Service_RegisterNotify-channel_transport
        run: echo "Test_HW0_Service_RegisterNotify-channel_transport, ${{needs.Test_HW0_Service_RegisterNotify-channel_transport.outputs.result}}" >> result.csv
      - name: Retrieve result of Test_HW0_Service_RegisterNotify-UDP_transport
        run: echo "Test_HW0_Service_RegisterNotify-UDP_transport, ${{needs.Test_HW0_Service_RegisterNotify-UDP_transport.outputs.result}}" >> result.csv
      - name: Retrieve result of Test_HW0_Messaging_Unicast-channel_transport
        run: echo "Test_HW0_Messaging_Unicast-channel_transport, ${{needs.Test_HW0_Messaging_Unicast-channel_transport.outputs.result}}" >> result.csv
      - name: Retrieve result of Test_HW0_Messaging_Unicast-UDP_transport
        run: echo "Test_HW0_Messaging_Unicast-UDP_transport, ${{needs.Test_HW0_Messaging_Unicast-UDP_transport.outputs.result}}" >> result.csv
      - name: Retrieve result of Test_HW0_Messaging_Unicast_Fail-channel_transport
        run: echo "Test_HW0_Messaging_Unicast_Fail-channel_transport, ${{needs.Test_HW0_Messaging_Unicast_Fail-channel_transport.outputs.result}}" >> result.csv
      - name: Retrieve result of Test_HW0_Messaging_Unicast_Fail-UDP_transport
        run: echo "Test_HW0_Messaging_Unicast_Fail-UDP_transport, ${{needs.Test_HW0_Messaging_Unicast_Fail-UDP_transport.outputs.result}}" >> result.csv
      - name: Retrieve result of Test_HW0_Messaging_Relaying-channel_transport
        run: echo "Test_HW0_Messaging_Relaying-channel_transport, ${{needs.Test_HW0_Messaging_Relaying-channel_transport.outputs.result}}" >> result.csv
      - name: Retrieve result of Test_HW0_Messaging_Relaying-UDP_transport
        run: echo "Test_HW0_Messaging_Relaying-UDP_transport, ${{needs.Test_HW0_Messaging_Relaying-UDP_transport.outputs.result}}" >> result.csv
      - name: Publish result as a release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "result.csv"
          allowUpdates: true
          tag: test-results
